[build]
  command = "pnpm run build"
  publish = "dist"

[functions]
  included_files = ["./.netlify/functions/server/sentry.server.config.mjs", "./.netlify/functions/server/node_modules/import-in-the-middle/hook.mjs"]